service: serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  profile: user1
  region: eu-west-1

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!node_modules/**"
    - "!dependencies/**"
    - "!*.zip"
    - "!**/event.json"
    - "!prisma/**"
    - "!lib/**"
    - "!scripts/**"
    - "!.step-functions-local/**"
    - "!.serverless/**"

custom:
  serverless-offline:
    httpPort: 4000
  stepFunctionsLocal:
    accountId: 101010101010
    region: us-east-1

functions:
  hello:
    handler: handler.hello
  ciao:
    handler: handler.ciao

stepFunctions:
  stateMachines:
    hellostepfunc1:
      type: EXPRESS
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld
        States:
          HelloWorld:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            Next: CiaoWorld
          CiaoWorld:
            Type: Task
            Resource: 
              Fn::GetAtt: [ciao, Arn]
            End: true
      events:
        - http:
            path: execute
            method: POST

plugins:
  - serverless-offline
  - serverless-step-functions
  - serverless-step-functions-local
  - serverless-pseudo-parameters
